"""
train_circuit_gnn.py
Trains CircuitGCN on circuit_graph_records.json (generated by circuit_dataset_generator.py).

Run: python train_circuit_gnn.py
Saves: circuit_gnn_model.pt  (best checkpoint by validation loss)

Expected time: ~20-40 min on CPU for 71k samples, 100 epochs.
"""

import json, os, math
import torch
import torch.nn.functional as F
from torch_geometric.data  import Data, Batch
from torch_geometric.loader import DataLoader
from circuit_graph_builder import build_graph, N_NODE_FEAT
from circuit_gnn_model     import CircuitGCN

RECORDS_PATH = "circuit_graph_records.json"
MODEL_PATH   = "circuit_gnn_model.pt"
BATCH_SIZE   = 64
EPOCHS       = 100
LR           = 1e-3
WEIGHT_DECAY = 1e-4
PATIENCE     = 8   # early stopping


# --------------------------------------------------------------------------- #
# Dataset
# --------------------------------------------------------------------------- #
class CircuitGraphDataset(torch.utils.data.Dataset):
    def __init__(self, records):
        self.records = records

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        r  = self.records[idx]
        g  = build_graph(r["components"], r["connections"])
        g.y_score   = torch.tensor([float(r["score"])], dtype=torch.float)
        g.y_verdict = torch.tensor(int(r["verdict"]),   dtype=torch.long)
        return g


# --------------------------------------------------------------------------- #
# Training helpers
# --------------------------------------------------------------------------- #
def run_epoch(model, loader, optimizer=None, train=True):
    model.train(train)
    total_loss = 0.0
    score_abs_err = 0.0
    correct = 0
    n_samples = 0

    for batch in loader:
        if train:
            optimizer.zero_grad()

        score_pred, verdict_pred = model(batch)
        y_score   = batch.y_score.squeeze()
        y_verdict = batch.y_verdict

        loss_score   = F.mse_loss(score_pred, y_score)
        loss_verdict = F.cross_entropy(verdict_pred, y_verdict)
        # Normalise MSE by 100^2 so both losses are ~same magnitude
        loss = 0.6 * (loss_score / 10000) + 0.4 * loss_verdict

        if train:
            loss.backward()
            optimizer.step()

        bs = y_score.size(0)
        total_loss    += loss.item() * bs
        score_abs_err += (score_pred - y_score).abs().sum().item()
        correct       += (verdict_pred.argmax(dim=1) == y_verdict).sum().item()
        n_samples     += bs

    return (total_loss / n_samples,
            score_abs_err / n_samples,
            correct / n_samples * 100)


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def train():
    print("=" * 60)
    print("  CircuitGCN Training")
    print("=" * 60)

    if not os.path.exists(RECORDS_PATH):
        print(f"[ERROR] {RECORDS_PATH} not found.")
        print("  Run: python circuit_dataset_generator.py  first.")
        return

    print(f"Loading {RECORDS_PATH} ...")
    with open(RECORDS_PATH, encoding="utf-8") as f:
        records = json.load(f)
    print(f"  {len(records):,} circuit records loaded.")

    dataset   = CircuitGraphDataset(records)
    n_train   = int(0.80 * len(dataset))
    n_val     = len(dataset) - n_train
    train_ds, val_ds = torch.utils.data.random_split(
        dataset, [n_train, n_val],
        generator=torch.Generator().manual_seed(42)
    )
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=256,        shuffle=False, num_workers=0)

    model     = CircuitGCN(in_feats=N_NODE_FEAT)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=3, factor=0.5, verbose=True)

    best_val_loss  = float("inf")
    no_improve     = 0

    print(f"\nTraining {len(train_ds):,} | Validation {len(val_ds):,}")
    print(f"Batch size: {BATCH_SIZE}  |  Max epochs: {EPOCHS}  |  LR: {LR}")
    print("-" * 60)

    for epoch in range(1, EPOCHS + 1):
        tr_loss, tr_mae, tr_acc = run_epoch(model, train_loader, optimizer, train=True)
        va_loss, va_mae, va_acc = run_epoch(model, val_loader,   train=False)
        scheduler.step(va_loss)

        improved = va_loss < best_val_loss
        if improved:
            best_val_loss = va_loss
            no_improve    = 0
            torch.save(model.state_dict(), MODEL_PATH)
            flag = " [SAVED]"
        else:
            no_improve += 1
            flag = ""

        if epoch % 5 == 0 or improved:
            print(f"Epoch {epoch:3d}  "
                  f"train_loss={tr_loss:.4f}  mae={tr_mae:.2f}  acc={tr_acc:.1f}%  |  "
                  f"val_loss={va_loss:.4f}  mae={va_mae:.2f}  acc={va_acc:.1f}%{flag}")

        if no_improve >= PATIENCE:
            print(f"\nEarly stopping at epoch {epoch} (no improvement for {PATIENCE} epochs).")
            break

    print(f"\n[DONE] Best model saved to: {MODEL_PATH}")
    print(f"       Best val_loss: {best_val_loss:.4f}")


if __name__ == "__main__":
    train()
